### ISSUE TITLE
선택지 UI 관련

### ISSUE THREAD

**Issue by hwabum** [hwabum/Riverport_Prototype#36]
![세로정렬](https://github.com/user-attachments/assets/c9c3317b-b048-467d-9b70-708e7bc6791a)

**Comment by hwabum** [comment]
짝수일때는 STARTING POINT (0, 0)에서 +-  (padding + box height/2) x 1, 2, 3 ......

홀수일때는 starting point (0, 0)에서 +- (padding + box height/2) x 0, 1, 2 .....

짝수일때는 만약 6번 배치한다면 위로 3번 밑으로 3번, 만약 4번 배치 한다면 위로 2번 밑으로 두번 = +-total count / 2

홀수일떄는 만약 3번 배치 한다면 중간 한번 위로 한번 밑으로 한번,

홀수일때 만약 5번 배치 한다면 중간 한번 위로 두번 밑으로 두번 = += (total count - 1) / 2

**Comment by hwabum** [comment]
@soohyun6035 
![image](https://github.com/user-attachments/assets/6bdebcd7-7bf6-4d8a-95ee-9309fde790ce)
![image](https://github.com/user-attachments/assets/9b6c9a18-fb6e-43e0-9d32-138c24e64d0d)
![image](https://github.com/user-attachments/assets/e83aca80-ac9c-4ef0-9c59-8b3d2e8e7fe2)

선택지을 해야 하는 장면에서는 획일적으로 텍스트 라인에 보여주기보단 이런 식으로 좀 연출하는게 어떨까요

**Comment by soohyun6035** [comment]
글씨가 길어짐에 따라서 정신없어보일수도있구요 정리가 안되보일수도있고 가시성이 떨어질뿐만아니라 아트에 가려질 확률이 큽니다 모바일 터치방식으로 게임을 하는게 저렇게 ui가 붙어있으면 선택했을때 잘못선택될수도있구요

**Comment by hwabum** [comment]
@soohyun6035 
그럼 그냥 선택지 1, 2, 3, 4 이런식으로 보여줘요 ? 텍스트 박스 안에?

**Comment by soohyun6035** [comment]
그렇죠

**Comment by hwabum** [comment]
ㅇㅋㅇㅋ 그게 사실 저도 제일 쉬워요

**Comment by hwabum** [comment]
단순하게 표현하되 상황에 따라 배치하는걸로.
어차피 인게임 샷 안나오면 지금 더 토론 하는건 무의미한거 같음.
